create_guest:
  path: /guest
  controller: App\Controller\Api\GuestController::createGuest
  methods: POST

get_guest:
  path: /guest/{id}
  controller: App\Controller\Api\GuestController::getGuest
  methods: GET